import * as fs from "fs";
import * as path from "path";

// Read the TSV file
const tsvPath = path.join(__dirname, "../public/badger/quali_schedule.tsv");
const tsvContent = fs.readFileSync(tsvPath, "utf-8");
const lines = tsvContent.trim().split("\n");

// Parse header to extract flight info
// Header: race | Eton Blue Stripe(1, 2, 3) | Eton Red Stripe(4, 5, 6) | Blue Stripe(7, 8, 9) | Green Stripe(10, 11, 12) | MTS Black Hulls(1, 2, 3) | MTS White Hulls(4, 5, 6)
const header = lines[0].split("\t");

// Define the flight mappings based on the header
// Columns 1-2: Eton flight (Blue Stripe 1,2,3 vs Red Stripe 4,5,6)
// Columns 3-4: Brunel flight (Blue Stripe 7,8,9 vs Green Stripe 10,11,12)
// Columns 5-6: MTS flight (Black Hulls 1,2,3 vs White Hulls 4,5,6)

interface HalfFlight {
    name: string;
    numbers: number[];
}

interface Flight {
    name: string;
    lhalf: HalfFlight;
    rhalf: HalfFlight;
    leftColumn: number;
    rightColumn: number;
}

const flights: Flight[] = [
    {
        name: "Eton",
        lhalf: { name: "Blue Stripe", numbers: [1, 2, 3] },
        rhalf: { name: "Red Stripe", numbers: [4, 5, 6] },
        leftColumn: 1,
        rightColumn: 2,
    },
    {
        name: "Brunel",
        lhalf: { name: "Blue Stripe", numbers: [7, 8, 9] },
        rhalf: { name: "Green Stripe", numbers: [10, 11, 12] },
        leftColumn: 3,
        rightColumn: 4,
    },
    {
        name: "MTS",
        lhalf: { name: "Black Hulls", numbers: [1, 2, 3] },
        rhalf: { name: "White Hulls", numbers: [4, 5, 6] },
        leftColumn: 5,
        rightColumn: 6,
    },
];

// Collect all unique teams from the data
const teams = new Set<string>();

// Parse data rows
interface RaceEntry {
    number: number;
    flightName: string;
    lteam: string;
    rteam: string;
}

const races: RaceEntry[] = [];

for (let i = 1; i < lines.length; i++) {
    const cols = lines[i].split("\t");
    const raceNumber = parseInt(cols[0], 10);

    if (isNaN(raceNumber)) continue;

    for (const flight of flights) {
        const lteam = cols[flight.leftColumn]?.trim();
        const rteam = cols[flight.rightColumn]?.trim();

        if (lteam && rteam) {
            teams.add(lteam);
            teams.add(rteam);
            races.push({
                number: raceNumber,
                flightName: flight.name,
                lteam,
                rteam,
            });
        }
    }
}

// Generate SQL
const sql: string[] = [];

sql.push("-- Import Badger Qualifying Schedule");
sql.push("-- Generated by scripts/import-badger-schedule.ts");
sql.push("");

// Insert flights (no need for halfflights in current schema)
sql.push("-- Insert flights");
for (const flight of flights) {
    sql.push(`INSERT INTO flight (name, lname, lnumbers, rname, rnumbers)
SELECT
  '${flight.name}',
  '${flight.lhalf.name}',
  ARRAY[${flight.lhalf.numbers.join(",")}],
  '${flight.rhalf.name}',
  ARRAY[${flight.rhalf.numbers.join(",")}]
WHERE NOT EXISTS (SELECT 1 FROM flight WHERE name = '${flight.name}');`);
}
sql.push("");

// Insert teams
sql.push("-- Insert teams");
const sortedTeams = Array.from(teams).sort();
for (const team of sortedTeams) {
    // Escape single quotes in team names
    const escapedTeam = team.replace(/'/g, "''");
    sql.push(
        `INSERT INTO team (name) VALUES ('${escapedTeam}') ON CONFLICT DO NOTHING;`
    );
}
sql.push("");

// Insert races
sql.push("-- Insert races");
for (const race of races) {
    const escapedLteam = race.lteam.replace(/'/g, "''");
    const escapedRteam = race.rteam.replace(/'/g, "''");
    sql.push(`INSERT INTO race (number, competition, league, flight, lteam, rteam)
SELECT
  ${race.number},
  'badger',
  'quali',
  (SELECT id FROM flight WHERE name = '${race.flightName}'),
  (SELECT id FROM team WHERE name = '${escapedLteam}'),
  (SELECT id FROM team WHERE name = '${escapedRteam}')
WHERE NOT EXISTS (
  SELECT 1 FROM race
  WHERE number = ${race.number}
  AND competition = 'badger'
  AND league = 'quali'
  AND flight = (SELECT id FROM flight WHERE name = '${race.flightName}')
);`);
}

console.log(sql.join("\n"));
